### ISSUE TITLE
I installed follwing directions but having these errors. How can I solve this ?

### ISSUE THREAD

**Issue by kash26** [bavix/laravel-admin-leaflet#5]
Symfony\Component\ErrorHandler\Error\FatalError
Access level to Bavix\Leaflet\LeafletMap::style() must be public (as in class Encore\Admin\Form\Field)
http://masterkash.develop:9001/admin/ets_physiques/1989/edit

**Comment by rez1dent3** [comment]
@kash26 Hello. I haven't used this package for over 1.5 years, it's not actively maintained. If you bring the PR, then I will release the tag. I have completely switched to laravel nova.

**Comment by kash26** [comment]
> @kash26 Hello. I haven't used this package for over 1.5 years, it's not actively maintained. If you bring the PR, then I will release the tag. I have completely switched to laravel nova.

Thanks much for your response.
